### ISSUE TITLE
Error: Discrete value supplied to continuous scale in plot_epimutations

### ISSUE THREAD

**Issue by prajkta9** [isglobal-brge/EpiMutations#27]
Hello,

I am using Epimutacions v1.4.0 and have encountered an error with the plot_epimutations. It says:
`Error: Discrete value supplied to continuous scale`

I did some digging and found that it only happens if there is NaN for some samples at the given epi-variant location (cpg ids) in the beta table. Is there a way to get past this error and plot? The value for mean and sd calculated using the function `betas_sd_mean` is NaN for those epi-variations.

**Comment by prajkta9** [comment]
A simple fix in the `betas_sd_mean` function for this issue:
```
mean <- rowMeans(betas, na.rm = T) 
sd <- apply(betas, 1, sd, na.rm = T)
```

**Comment by dpelegri** [comment]
Hello @prajkta9 

Thanks for using epimutacions, 
I fixed the bug. Could you check if you can make the plot?

Best,

Dolors

**Comment by prajkta9** [comment]
Thanks, but I still get the error. I tried to force-install the package again, but is there any other way to update it?

**Comment by dpelegri** [comment]
Hi @prajkta9,

Are you using the Bioconductor version?, if so, the changes are not propagated yet. If you want, you can install the content of the devel version directly from github with the command:

`devtools::install_github("isglobal-brge/epimutacions@devel")`

the current version under development is 1.5.2, which corresponds to the next release of Bioconductor (release 3.18). In this version the bug in the function `plot_epimutacions()` should be fixed.

**Comment by prajkta9** [comment]
I tried this version 1.5.2, but the error is still there.

**Comment by dpelegri** [comment]
Could you attach a sample dataset or a .Rda file with the object?

**Comment by prajkta9** [comment]
I cannot share the data. I tried the plot_epimutations script, and the`emptySamples` vector is `NA` for all samples. Additionally, mean and all sd vectors are also `NA`.

**Comment by dpelegri** [comment]
Hi @prajkta9 ,

The first solution with about more than 20% NA was not working, I have applied the na.rm, now it should work. Could you test it with your data?

Best,

**Comment by dpelegri** [comment]
Changes are in github -> devel branch

**Comment by prajkta9** [comment]
Works perfectly now, thanks.
